### ISSUE TITLE
Typo in description of HeatPort model in Rod.mo

### ISSUE THREAD

**Issue by modelica2015** [modelica2015/ModelicaBook#10]
In `ModelicaByExample.Subsystems.HeatTransfer.Components.Rod.mo`

`Modelica.Thermal.HeatTransfer.Interfaces.HeatPort_a ambient "Thermal connector for rod end 'a'` --> `"Thermal connector to ambient"`

**Comment by dietmarw** [comment]
This issue was moved to xogeny/ModelicaBook#268
