### ISSUE TITLE
Typo in quoted Modelica code of comonent_models.rst

### ISSUE THREAD

**Issue by modelica2015** [modelica2015/ModelicaBook#5]
`text/source/components/components/component_models.rst`
In Generated Equations and Conservation:
  `ground.flange_a.phi = damper2.flange_b;` --> `ground.flange_a.phi = damper2.flange_b.phi;`
 and
 `damper2.flange_b.phi = spring2.flange_b;` --> `damper2.flange_b.phi = spring2.flange_b.phi;`

**Comment by xogeny** [comment]
This is a duplicate of #1.
