### ISSUE TITLE
Add missing index references for import

### ISSUE THREAD

**Issue by xogeny** [modelica2015/ModelicaBook#8]
There are three ways to `import` discussed in `text/source/components/packages/importing.rst` (normal, short hand, wildcard).  None of them appears in the index.  This is because [the markup to add an index entry](http://sphinx-doc.org/markup/misc.html#directive-index) is missing.  This should be added.  At a minimum, there should be at least one entry in the index pointing to this section of the book for more information about `import`.  Ideally, the discussion of each different type of import should be referenced distinctly (leading to three specialized index entries, one for each type of import).

**Comment by dietmarw** [comment]
This issue was moved to xogeny/ModelicaBook#273
