### ISSUE TITLE
Improve wording in "subsystems/power_supply"

### ISSUE THREAD

**Issue by modelica2015** [modelica2015/ModelicaBook#9]
In `text/components/subsystems/power_supply.rst`

Below Simulate FlatCircuit:
 "(because the load connecting the switch to the power supply is open)" --> "(because the switch to the power supply is open)"

**Comment by xogeny** [comment]
This is a duplicate of #3.

**Comment by dietmarw** [comment]
This issue was moved to xogeny/ModelicaBook#266
